apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  namespace: teamcity
  labels:
    app: tc-agent
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc-agent
  template:
    metadata:
      labels:
        app: tc-agent
    spec:
      containers:
      - name: teamcity-agent
        image: jetbrains/teamcity-agent
        volumeMounts:
        - name: tc-agent-conf
          mountPath: /data/teamcity_agent/conf
        env:
        - name: SERVER_URL
          value: 192.168.99.100:8111
      volumes:
      - name: tc-agent-conf
        hostPath:
          path: /host/k8s-demo/tc/agent-conf
          type: Directory


