apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo-app
  labels:
    app: nginx
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-www
          mountPath: /home
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: my-site
            path: my-site.conf
      - name: nginx-www
        configMap:
          name: nginx-config
          items:
          - key: index
            path: index.html
